name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v3

    - shell: bash
      run: docker compose build dev

    - shell: bash
      run: docker compose run dev ci